spring:
  profiles:
    include: api-dev
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
      enabled: true
media:
  upfile:
    path: /opt/docker/javaProject/everyService/upload
    code: uploadfilecode
    url: http://localhost:8080/irs/upload/
    fileSize: 5MB